### ISSUE TITLE
Chrome 64 issue

### ISSUE THREAD

**Issue by oskenneth** [livestyle/chrome#32]
Extension no longer reads external stylesheet with the following error...

> Error in event handler for runtime.onMessage: SecurityError: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules

Note: Allow access to files option already checked in the extension preference

**Comment by luiscabus** [comment]
@sergeche This is the best plugin front-end developers ever!! Please don't let it fade. There's no such a great plugin anywhere else with such a seamless workflow. It seems that some workaround needs to be done in order for it to work again on chrome.

**Comment by sergeche** [comment]
Unfortunately, there’s no simple workaround for this problem :( I still hope I can find time and funding to develop this project

**Comment by doublecream** [comment]
@sergeche - why don't we crowdfund further dev? Livestyle is unique and 100% necessary... keep going man! I'm just returning to webdev after a 1 year break and now have to develop a long project... it's a nightmare to even think of doing it without Livestyle!

**Comment by oskenneth** [comment]
@sergeche @doublecream crowdfund would be a great idea if you got the time! livestyle truly raised the bar too high, there is simply no other plugin even come close to it!

**Comment by sergeche** [comment]
I’ve tried crowdfunding already and it failed :( Anyways, I’m slowly moving towards my main Emmet project release with another attempt to get support from community via OpenCollective, and if I get enough funding, I’ll continue this project development

**Comment by doublecream** [comment]
I'm sorry to hear crowdfunding didn't work out :Sounds like you've got a plan though so "strength and honour" to you and best of luck with Emmet...

**Comment by Kritnich** [comment]
I know this is very late, but for future reference for anyone else who might hit this issue: https://github.com/chromium/chromium/commit/a4ebe08c91e29140e700c7bae9b94f27a786d1ca

**Comment by blvz** [comment]
FWIW, I fixed it with `browser-sync`.

```sh
npm install -g browser-sync
browser-sync start --config bs-config.js --proxy 'localhost:8080' --files src
```

```js
module.exports = {
  cors: true,
  rewriteRules: [
    {
      match: /(<link.+rel=["']stylesheet["'])/g,
      replace: '$1 crossorigin',
    },
  ],
}
```

**Comment by liquidmetalrob** [comment]
> I’ve tried crowdfunding already and it failed :( Anyways, I’m slowly moving towards my main Emmet project release with another attempt to get support from community via OpenCollective, and if I get enough funding, I’ll continue this project development

That's a shame that you had to stop this project because it's very impressive.

I've been working on my own project that does a similar thing for Sass indented syntax in a more traditional way by using the normal node-sass converter to detect when a Sass file is saved and then converting to CSS and then it all also detects when a CSS file is saved, but it only accepts it if it does not come right after a Sass change, so that it can avoid a loop. My script also inserts CSS rules back into the Sass file, but it is just a node script and so there is always a slight delay, so to see the LiveStyle extension working so quickly is amazing.

I think I am going to study your code and try to learn some things about how it works and perhaps I may be able to contribute.
